name: petlife_mobile_app
description: PetLife mobile application.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.3
  file_picker: ^11.0.2
  video_player: ">=2.9.5 <2.10.0"
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  csp_amap_flutter_location: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
